use super::*;

#[derive(Debug, Clone)]
pub enum Message {
    SelectSection(Section),
    ToggleTheme,
    LanguageSelected(Language),
    FontPreferenceSelected(UiFontPreference),
    RunQuickAction(QuickAction),
    ConnectionDriverSelected(DatabaseDriver),
    ConnectionFieldChanged(ConnectionField, String),
    ConnectionSslToggled(bool),
    ConnectionSshToggled(bool),
    NewConnectionProfile,
    ConnectionSearchChanged(String),
    ReloadConnectionProfiles,
    ToggleConnectionFilter,
    RequestTestConnection,
    CloseTestResult,
    ConnectionTestFinished(u64, Result<ConnectionTestReport, Vec<String>>),
    SaveConnectionProfile,
    ConnectConnectionProfile,
    ConnectionConnectFinished(u64, Result<ConnectionTestReport, Vec<String>>),
    SelectConnectionProfile(usize),
    RequestDeleteConnection(usize),
    CancelDeleteConnection,
    ConfirmDeleteConnection,
    CancelSchemaDelete,
    ConfirmSchemaDelete,
    SchemaDeleteFinished(String, SchemaDeletionKind, QueryExecutionOutcome),
    RefreshQuerySchema,
    QuerySchemaRefreshed(SchemaLoadOutcome),
    QuerySchemaObjectColumnsLoaded(String, Result<Vec<SchemaObject>, Vec<String>>),
    UseQuerySchemaObject(usize),
    ToggleSchemaObject(usize),
    ToggleSchemaObjectMenu(usize),
    RequestCreateTable,
    RunDatabaseAction(DatabaseAction),
    RunDatabaseObjectAction(DatabaseAction, usize),
    DatabaseEditFieldChanged(DatabaseEditField, String),
    CancelDatabaseEdit,
    SubmitRenameDatabase,
    RenameDatabaseFinished(String, String, QueryExecutionOutcome),
    DatabaseDetailsLoaded(String, Result<DatabaseDetails, Vec<String>>),
    SubmitAlterDatabaseCharset,
    AlterDatabaseCharsetFinished(String, QueryExecutionOutcome),
    CreateDatabaseFieldChanged(CreateDatabaseField, String),
    CancelCreateDatabase,
    SubmitCreateDatabase,
    CreateDatabaseFinished(String, QueryExecutionOutcome),
    CreateTableFieldChanged(CreateTableField, String),
    CreateTableColumnFieldChanged(usize, CreateTableColumnField, String),
    CreateTableIndexFieldChanged(usize, CreateTableIndexField, String),
    CreateTableConstraintFieldChanged(usize, CreateTableConstraintField, String),
    CreateTableTabSelected(CreateTableTab),
    AddCreateTableColumn,
    InsertCreateTableColumnAfter(usize),
    RemoveCreateTableColumn(usize),
    MoveCreateTableColumn(usize, i32),
    AddCreateTableIndexForColumn(usize),
    AddCreateTableIndex,
    RemoveCreateTableIndex(usize),
    AddCreateTableConstraint,
    RemoveCreateTableConstraint(usize),
    CancelCreateTable,
    SubmitCreateTable,
    CreateTableFinished(String, QueryExecutionOutcome),
    RunTableAction(TableAction, usize),
    TableRowsLoaded(String, usize, QueryExecutionOutcome),
    TableDetailsLoaded(String, Result<TableDetails, Vec<String>>),
    TableEditFieldChanged(TableEditField, String),
    AlterTableFieldChanged(AlterTableField, String),
    ToggleAlterTableIndexColumn(String),
    PrepareAlterTableIndex,
    ClearAlterTableIndex,
    AppendCreateTableIndexColumn(usize, String),
    AlterTableTabSelected(AlterTableTab),
    InsertAlterTableColumnAfterSelection,
    RemoveAlterTableColumn(usize),
    RemoveSelectedAlterTableColumn,
    RevertSelectedAlterTableChange,
    RevertAllAlterTableChanges,
    MoveSelectedAlterTableColumn(i32),
    SelectAlterTableColumn(usize),
    AddAlterTableIndexForColumn(usize),
    CancelTableEdit,
    SubmitRenameTable,
    RenameTableFinished(String, String, QueryExecutionOutcome),
    SubmitAlterTable,
    AlterTableFinished(String, QueryExecutionOutcome),
    AlterTableColumnFieldChanged(usize, CreateTableColumnField, String),
    SystemMetricsTick,
    DragWindow,
    MinimizeWindow,
    CloseWindow,
}
